#pragma once
#include "stdafx.h"
#include <WinIoCtl.h>

//定义用于应用程序和驱动程序通信的宏，这里使用的是缓冲区读写方式
#define	IO_INSERT_HIDE_PROCESS			CTL_CODE(FILE_DEVICE_UNKNOWN, 0x801, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define	IO_REMOVE_HIDE_PROCESS			CTL_CODE(FILE_DEVICE_UNKNOWN, 0x802, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define	IO_INSERT_PROTECT_PROCESS		CTL_CODE(FILE_DEVICE_UNKNOWN, 0x803, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define	IO_REMOVE_PROTECT_PROCESS		CTL_CODE(FILE_DEVICE_UNKNOWN, 0x804, METHOD_BUFFERED, FILE_ANY_ACCESS)

const TCHAR szSysPath[]=_T("\\eprotect.sys");
const TCHAR szSvcName[]=_T("EProcess");
const TCHAR szSymLinkName[]=_T("\\\\.\\SSDTProcess");